name: e_gift_shoppe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-444.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  intl: ^0.15.7

flutter:
  uses-material-design: true
